name: Test Scalr CLI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: buzzy/scalr-action@v0.10.0
        with:
          scalr_hostname: 'daniele.scalr.io'
          scalr_token: ${{ secrets.SCALR_TOKEN }}
          scalr_workspace: ws-u7f44t3oldrj7r0
          terraform_wrapper: false
  
      - run: scalr -version
      - run: terraform -version
