name: Test Scalr CLI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: buzzy/scalr-action@v0.5.0
        with:
          scalr_hostname: 'example.scalr.io'
          scalr_token: "xxx"
          terraform_version: 1.2.0
          terraform_wrapper: false
  
      - run: scalr
        shell: bash
