name: Test Wrapper

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: buzzy/scalr-action@v1
        with:
          scalr_hostname: 'example.scalr.io'
          scalr_token: "xxx"
          terraform_version: 1.2.0
          terraform_wrapper: false
  
      - run: terraform init
