name: Test Scalr CLI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: 'macos-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: buzzy/scalr-action@v0.6.0
        with:
          scalr_hostname: 'example.scalr.io'
          scalr_token: "xxx"
          terraform_wrapper: false
  
      - run: scalr -version
      - run: terraform -version
