name: Test Outputs

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: buzzy/scalr-action@v0.4.0
        with:
          scalr_hostname: 'example.scalr.io'
          scalr_token: "xxx"
          terraform_version: 1.2.0
          terraform_output: false
  
      - run: terraform init

      - id: plan
        run: terraform plan

      - id: apply
        run: terraform apply -auto-approve

      - run: echo ${{ steps.apply.outputs.test_var }}
